move 3 deps out of doc subpkg
thus fixing running testsuite with doc pkg disabled:
ImportError: No module named oslo_config
ImportError: No module named fasteners
ImportError: No module named oslo_utils

Change-Id: I24912a6249e0d3933ee4ba6dd6f1bf5ab611ce91
(cherry picked from commit dc6f10e34f9d34ee1b5e2565be27a13407eb22a2)